# security conf
export SECRET_KEY='YOUR_VALUE_HERE'
export ALLOWED_HOSTS='["YOUR_VALUE_HERE", "YOUR_VALUE_HERE", "YOUR_VALUE_HERE"]'
export DEBUG=True

# DB conf
export DB_NAME='YOUR_VALUE_HERE'
export DB_USER='YOUR_VALUE_HERE'
export DB_PASSWORD='YOUR_VALUE_HERE'
export DB_HOST='localhost'
export DB_PORT=''

# STATIC AND MEDIA URL  
export STATIC_URL=''
export MEDIA_URL=''
# STATIC AND MEDIA ROOT 
export STATIC_ROOT=''
export MEDIA_ROOT=''
