# Generated by Django 2.1.2 on 2018-10-24 15:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManyxProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('snapshot', models.ImageField(upload_to='snapshots')),
                ('start_date', django_jalali.db.models.jDateField()),
                ('end_date', django_jalali.db.models.jDateField(null=True)),
                ('live_url', models.URLField(blank=True)),
                ('git_repository_url', models.URLField(blank=True)),
                ('estimated_hours', models.PositiveIntegerField(null=True)),
                ('team_members', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
