# Generated by Django 2.1.2 on 2018-10-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_manyxproject_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyxproject',
            name='snapshot',
            field=models.ImageField(null=True, upload_to='snapshots'),
        ),
    ]
