# Generated by Django 2.1.2 on 2018-10-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181025_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyxproject',
            name='live_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
