# Generated by Django 2.1.2 on 2018-10-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181025_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyxproject',
            name='git_repository_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
