# Generated by Django 2.1.2 on 2018-10-25 13:44

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181025_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyxproject',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
