# Generated by Django 2.1.2 on 2018-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181025_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyxproject',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
