# Generated by Django 2.1.2 on 2018-11-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20181030_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyxproject',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
