# Generated by Django 2.1.2 on 2018-11-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20181103_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='manyxproject',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='adfadf-adfadf', unique=True),
            preserve_default=False,
        ),
    ]
