# Generated by Django 2.1.2 on 2018-11-29 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('last_modified_datetime', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('auther', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
