# Generated by Django 2.1.2 on 2018-12-01 21:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20181201_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
