# Generated by Django 2.1.2 on 2018-12-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blog_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publication_date',
            new_name='publication_datetime',
        ),
    ]
