# Generated by Django 2.1.2 on 2018-11-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyx', '0002_auto_20181104_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='manyxuser',
            name='full_name_fa',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
