# Generated by Django 2.1.2 on 2019-01-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyx', '0004_manyxuser_description_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manyxuser',
            name='full_name_fa',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
