# Generated by Django 2.1.2 on 2018-11-30 21:02

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181129_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publication_date',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
    ]
