# Generated by Django 2.1.2 on 2018-12-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181201_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
