# Generated by Django 2.1.2 on 2018-12-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20181201_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
