# Generated by Django 2.1.2 on 2018-10-24 14:12

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('manyx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manyxuser',
            name='since',
            field=django_jalali.db.models.jDateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
