# Generated by Django 2.1.2 on 2018-10-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manyx', '0002_manyxuser_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manyxuser',
            name='since',
        ),
    ]
