# Generated by Django 2.1.2 on 2018-10-31 06:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manyx', '0003_remove_manyxuser_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialReferCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('account_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='manyxuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='manyxuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='manyxuser',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='manyxuser',
            name='twitter',
        ),
        migrations.AddField(
            model_name='manyxuser',
            name='social',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='socialrefercounter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
