# Generated by Django 2.1.2 on 2018-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyx', '0004_auto_20181031_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialrefercounter',
            name='counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
