# Generated by Django 2.1.2 on 2018-10-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyx', '0005_socialrefercounter_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manyxuser',
            name='website',
        ),
        migrations.AlterField(
            model_name='socialrefercounter',
            name='account',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='socialrefercounter',
            name='account_id',
            field=models.CharField(max_length=200),
        ),
    ]
