version: '3'

# docker file ver 1.0 : By Amirhossein Saemi
services:
  web:
    restart: always
    build: .
    ports:
      - 8000:8000
    networks:
      manyx_network:
    depends_on:
      - db
    volumes:
      - ./:/manyx_core
      - ../development_data/static:/manyx/static/
      - ../development_data/media:/manyx/media/
    command: bash -c "python manage.py migrate --noinput && python manage.py shell < entrypoint.py && python manage.py runserver 0.0.0.0:8000"
    environment:
      # security
      - MAINTENANCE=False
      - DEBUG_IPS=["debug_ip"]
      - DEBUG=True
      - SECRET_KEY=top_secret
      - ALLOWED_HOSTS=["127.0.0.1"]
      # database
      - DB_NAME=some_db
      - DB_USER=some_user
      - DB_PASSWORD=some_password
      - DB_HOST=db
      - DB_PORT=5432
      # STATIC AND MEDIA ROOT
      - STATIC_ROOT=/manyx/static/
      - MEDIA_ROOT=/manyx/media/
      # STATIC AND MEDIA URL
      - STATIC_URL=/static/
      - MEDIA_URL=/media/
  db:
    restart: always
    image: postgres:11.1
    environment:
      - POSTGRES_USER=some_user
      - POSTGRES_PASSWORD=some_password
      - POSTGRES_DB=some_db
    networks:
      manyx_network:
    volumes:
      - ../development_data/postgres:/var/lib/postgresql/data


networks:
  manyx_network:
